services:
  app:
    build: .
    networks:
      - student-data-network
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: student_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
    networks:
      - student-data-network
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data

networks:
  student-data-network:
    driver: bridge

volumes:
  db-volume: