services:
  app:
    build: .
    networks:
      - student-data-network
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES-DB: student_data
      POSTGRES-USER: satya
      POSTGRES-PASSWORD: abcd1234
    networks:
      - student-data-network
    ports:
      - "5432:5432"

networks:
  student-data-network:

